 stages:
  - deploy

 Application Deployment Production:

    stage: deploy
    variables:
      GIT_DEPTH: 1
      GIT_STRATEGY: clone
    script:
     - export SHORT_SHA=$(echo $CI_COMMIT_SHORT_SHA)
     - export IMAGE_TAG="v1.0.0-$SHORT_SHA"
     - docker login https://10.38.13.140:5000 -u nutanix -p nx2Tech806!
     - docker login -u ariefpri1122 -p nutanix/4u
     - cp Dockerfile.$CI_COMMIT_BRANCH Dockerfile
     - docker build -t arief_laravel_$CI_COMMIT_BRANCH .
     - docker tag arief_laravel_$CI_COMMIT_BRANCH 10.38.13.140:5000/library/arief_laravel_$CI_COMMIT_BRANCH:$IMAGE_TAG
     - docker push 10.38.13.140:5000/library/arief_laravel_$CI_COMMIT_BRANCH:$IMAGE_TAG
     
    only:
      refs:
        - development
        - stagging
        - master
      variables:
        - $CI_COMMIT_MESSAGE =~ /nyalip/
    tags:
      - vm-runner
